name: ✨ Feature Request
description: Suggest a new feature or enhancement for Kairos
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible to help us understand your request.

  - type: checkboxes
    id: terms
    attributes:
      label: Prerequisites
      description: Please confirm the following before submitting
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I have read the [contributing guidelines](../../CONTRIBUTING.md)
          required: true
        - label: This is a feature request, not a bug report
          required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of Kairos would this feature affect?
      options:
        - Backend API
        - Frontend UI
        - Database/Migrations
        - Authentication
        - Scheduling Engine
        - AI Assistant
        - Docker/Deployment
        - Documentation
        - Mobile App
        - Integration
        - Other
    validations:
      required: true

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature is this?
      options:
        - New functionality
        - Enhancement to existing feature
        - Performance improvement
        - Developer experience improvement
        - User experience improvement
        - Integration with external service
        - Other
    validations:
      required: true

  - type: textarea
    id: problem-statement
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What pain point are you experiencing?
      placeholder: Describe the problem or pain point this feature would address...
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented
      placeholder: Describe your proposed solution in detail...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Describe any alternative solutions or workarounds you've considered
      placeholder: What alternatives have you considered?

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Provide specific use cases where this feature would be valuable
      placeholder: |
        1. As a [user type], I want to [goal] so that [benefit]
        2. When [scenario], I need [functionality] to [outcome]
    validations:
      required: true

  - type: dropdown
    id: user-type
    attributes:
      label: User Type
      description: Who would primarily benefit from this feature?
      options:
        - Individual users
        - Team users
        - Developers/Integrators
        - System administrators
        - All users
        - Other

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Nice to have
        - Would be helpful
        - Important for my workflow
        - Critical/Blocking
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: What criteria must be met for this feature to be considered complete?
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
        - [ ] Criterion 3

  - type: textarea
    id: mockups
    attributes:
      label: Mockups/Screenshots
      description: If applicable, add mockups, wireframes, or screenshots to illustrate your idea
      placeholder: Drag and drop images here or paste them

  - type: textarea
    id: technical-considerations
    attributes:
      label: Technical Considerations
      description: Are there any technical aspects, constraints, or dependencies to consider?
      placeholder: Any technical considerations, API changes, performance impacts, etc.

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, examples, or references about the feature request
      placeholder: |
        - Links to similar features in other applications
        - Research or documentation
        - Community feedback
        - Any other relevant information

